approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
    -
        name: devs
        required: 2
        members:
            - carlossuperlogica
            - ademilson
            - adenilsonoliveira
            - alantavares
            - dhenrique
            - gutopolewacz
            - isaqued
            - luiscera
        conditions:
            files:
                - "!linux/*"            
    -
        name: infra
        required: 1
        members:
            - carlossuperlogica
            - ademilson
            - adenilsonoliveira
            - alantavares
            - dhenrique
            - gutopolewacz
            - isaqued
            - luiscera            
        conditions:
            files:
                - "linux/*"
